# Generated by Django 3.1 on 2020-08-10 02:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('post_image', models.ImageField(upload_to='assets/img/posts')),
                ('pub_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date Published')),
            ],
        ),
    ]
